backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

i18n:
  structure: multiple_folders
  locales: [en, de, fr, nv, bn, es, hi, km, ko, tl, vi, ypk, zh, zh-hans]

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Register"
    name: "register"
    folder: "src/register"
    create: true
    editor:
      preview: true
    i18n: true
    fields:
      - { label: "State Name", name: "state_name", widget: "string" }
      - { label: "State Abbreviation", name: "state_abbreviation", widget: "string" }
      - { label: "Registration Type", name: "registration_type", widget: "select", options: ["online", "by-mail", "in-person", "not-needed"] }
      - label: "Home Page"
        i18n: true
        name: "home_page"
        widget: "object"
        fields: 
          - {label: "URL", i18n: true, name: "url", widget: "string"}
          - {label: "Chosen Language", i18n: true, name: "registration_type", widget: "select", options: ["linked", "selectable", "not-available"], hint: "Does the URL link to a page in the user's chosen language? Will the user have an option to select their language?" }
      - label: "Registration Page"
        i18n: true
        name: "registration_page"
        widget: "object"
        fields: 
          - {label: "URL", i18n: true, name: "url", widget: "string"}
          - {label: "Chosen Language", i18n: true, name: "registration_type", widget: "select", options: ["linked", "selectable", "not-available"], hint: "Does the URL link to a page in the user's chosen language? Will the user have an option to select their language?" }
      - label: "More Info Page"
        i18n: true
        name: "more_info_page"
        widget: "object"
        fields: 
          - {label: "URL", i18n: true, name: "url", widget: "string"}
          - {label: "Chosen Language", i18n: true, name: "registration_type", widget: "select", options: ["linked", "selectable", "not-available"], hint: "Does the URL link to a page in the user's chosen language? Will the user have an option to select their language?" }
      - label: 'Deadline for Online Voter Registration'
        name: 'online_deadline'
        widget: 'date'
        default: ''
        format: 'MMM Do YY'
      - label: 'Deadline for In-Person Voter Registration'
        name: 'in_person_deadline'
        widget: 'date'
        default: ''
        format: 'MMM Do YY'
      - label: 'Deadline for Mail-In Voter Registration Postmark'
        name: 'mail_postmarked_deadline'
        widget: 'date'
        default: ''
        format: 'MMM Do YY'
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Description", name: "description", widget: "string", i18n: true }
      - { label: "Author", name: "author", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
